// ============================================================
// LËGĒNDÃRY BØT — Deploy Template
// ============================================================
// 1. Fill in your details in config.js (sessionId, name, etc.)
// 2. Do NOT edit this file unless you know what you're doing.
// 3. Run: npm install, then node index.js
// ============================================================

const fs = require('fs');
const path = require('path');
const axios = require('axios');
const {
    default: makeWASocket,
    useMultiFileAuthState,
    fetchLatestBaileysVersion,
    makeInMemoryStore,
    Browsers,
    DisconnectReason
} = require('@boruto_vk7/baileys');
const { Boom } = require('@hapi/boom');
const chalk = require('chalk');
const pino = require('pino');
const { smsg } = require('./storage');

let config;
try {
    config = require('./config');
} catch (e) {
    console.log(chalk.red('❌ Could not find config.js.'));
    console.log(chalk.yellow('   Copy config.example.js to config.js, fill in your details, and try again.'));
    process.exit(1);
}

function validateConfig(cfg) {
    const problems = [];

    if (!cfg.sessionId || cfg.sessionId === 'PASTE_YOUR_SESSION_ID_HERE') {
        problems.push('sessionId is missing — pair on the site first and paste your session ID in config.js.');
    }

    if (!cfg.ownerName || cfg.ownerName === 'PASTE_YOUR_NAME_HERE') {
        problems.push('ownerName is missing — add your name in config.js.');
    }

    if (!cfg.botName || typeof cfg.botName !== 'string' || !cfg.botName.trim()) {
        problems.push('botName is missing or empty — give your bot a name in config.js.');
    }

    if (!cfg.prefix || typeof cfg.prefix !== 'string' || cfg.prefix.includes(' ') || cfg.prefix.length > 3) {
        problems.push('prefix looks invalid — it should be a short symbol with no spaces, like "." or "!".');
    }

    if (typeof cfg.publicMode !== 'boolean') {
        problems.push('publicMode should be true or false (no quotes) in config.js.');
    }

    if (cfg.sudoNumbers && !Array.isArray(cfg.sudoNumbers)) {
        problems.push('sudoNumbers should be a list like ["234xxxxxxxxxx"], not a single value.');
    } else if (Array.isArray(cfg.sudoNumbers)) {
        for (const n of cfg.sudoNumbers) {
            if (typeof n !== 'string' || !/^\d+$/.test(n)) {
                problems.push(`sudoNumbers has an invalid entry: "${n}" — use digits only, no + or spaces.`);
            }
        }
    }

    return problems;
}

const configProblems = validateConfig(config);
if (configProblems.length) {
    console.log(chalk.red(`❌ Found ${configProblems.length} problem(s) in config.js:\n`));
    configProblems.forEach((p, i) => console.log(chalk.yellow(`  ${i + 1}. ${p}`)));
    console.log(chalk.yellow('\nFix these in config.js and run again.'));
    process.exit(1);
}

console.log(chalk.green('✅ config.js looks good.'));

// The base URL of LËGĒNDÃRY LAB™'s session API — do not change
const API_BASE_URL = 'https://your-server-domain.com'; // <-- replace with your real server URL

const SESSION_DIR = path.join(__dirname, 'session');
const store = makeInMemoryStore ? makeInMemoryStore({ logger: pino().child({ level: 'silent', stream: 'store' }) }) : null;

async function fetchAndBuildSession() {
    if (!config.sessionId || config.sessionId === 'PASTE_YOUR_SESSION_ID_HERE') {
        console.log(chalk.red('❌ No session ID set in config.js. Pair on the site first.'));
        process.exit(1);
    }

    console.log(chalk.yellow('🔄 Fetching your session...'));

    let response;
    try {
        response = await axios.get(`${API_BASE_URL}/api/session/${config.sessionId}`);
    } catch (e) {
        console.log(chalk.red(`❌ Could not fetch session: ${e.response?.data?.error || e.message}`));
        process.exit(1);
    }

    const { files } = response.data;

    if (!fs.existsSync(SESSION_DIR)) {
        fs.mkdirSync(SESSION_DIR, { recursive: true });
    }

    for (const [filename, content] of Object.entries(files)) {
        fs.writeFileSync(path.join(SESSION_DIR, filename), content, 'utf-8');
    }

    console.log(chalk.green('✅ Session restored locally.'));
}

async function startBot() {
    await fetchAndBuildSession();

    const { state, saveCreds } = await useMultiFileAuthState(SESSION_DIR);
    const { version } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        version,
        auth: state,
        browser: Browsers.macOS(config.botName || 'LËGĒNDÃRY BØT'),
        printQRInTerminal: false
    });

    // Make config available globally so case.js can read prefix/publicMode/sudoNumbers
    global.botConfig = config;
    sock.public = config.publicMode ?? false;

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update;

        if (connection === 'open') {
            console.log(chalk.bgGreen.black(`✅ ${config.botName || 'Bot'} connected successfully!`));
        }

        if (connection === 'close') {
            const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
            console.log(chalk.red(`Connection closed. Reconnecting: ${shouldReconnect}`));
            if (shouldReconnect) startBot();
        }
    });

    if (store) store.bind(sock.ev);

    // Hook up the command handler — matches the exact pattern case.js expects
    sock.ev.on('messages.upsert', async (chatUpdate) => {
        try {
            const nexusboijid = chatUpdate.messages[0];
            if (!nexusboijid.message || !Object.keys(nexusboijid.message).length) return;

            nexusboijid.message = (Object.keys(nexusboijid.message)[0] === 'ephemeralMessage')
                ? nexusboijid.message.ephemeralMessage.message
                : nexusboijid.message;

            if (!sock.public && !nexusboijid.key.fromMe && chatUpdate.type === 'notify') return;
            if (nexusboijid.key.id.startsWith('BAE5') && nexusboijid.key.id.length === 16) return;

            const m = smsg(sock, nexusboijid, store);
            require('./case')(sock, m, chatUpdate, store);
        } catch (err) {
            console.log(chalk.red(`Message handler error: ${err.message}`));
        }
    });
}

startBot().catch((e) => {
    console.log(chalk.red(`❌ Failed to start bot: ${e.message}`));
    process.exit(1);
});
